config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    get 'media/feed', to: 'media#feed'
    get 'users/search', to: 'users#search'
    resources :comments, only: [:show, :index, :create, :destroy]
    resources :followers, only: [:show, :index, :create, :destroy]
    resources :media, only: [:show, :create, :destroy, :update]
    resources :likes, only: [:show, :index, :create, :destroy]
    resources :pictures, only: [:show, :index, :create, :destroy]
    resources :users, only: [:show, :index]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, uniqueness: true
  validates :password_digest, :session_token, :quote, presence: true
  validates :password, length:{minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  attr_accessor :password

  has_many(
    :comments,
    class_name: :Comment,
    foreign_key: :id,
    primary_key: :id,
    dependent: :destroy
  )

  has_one :picture, as: :imageable

  has_many(
    :active,
    class_name: :Follower,
    foreign_key: :follower_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :passive,
    class_name: :Follower,
    foreign_key: :followee_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :following, through: :active, source: :followee
  has_many :followers, through: :passive, source: :follower

  has_many(
    :likes,
    class_name: :Like,
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :liked_posts, through: :likes, source: :post

  has_many(
    :posts,
    class_name: :Medium,
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy
  )


  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username,password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def photo_likes_hash
    zipped_likes = likes.pluck(:media_id).zip(likes)
    likes_hash = {}

    zipped_likes.each do |(id, like)|
      likes_hash[id] = like
    end

    likes_hash
  end

  def following_hash
    zipped_following = active.pluck(:follower_id).zip(active)
    likes_hash = {}

    zipped_following.each do |(follower_id, active)|
      likes_hash[follower_id] = active
    end

    zipped_following
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def feed
    following_ids = Follower.select(:followee_id).where(follower_id: self.id).map(&:followee_id)
    following_ids << self.id
    Medium.includes(:likers, :picture, :author, comments: [:author]).where(:author_id => following_ids)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.includes(:picture, :followers, :following, posts: [:likers, :comments, :author, :picture, :likes]).all
    if logged_in?
        @following_hash = current_user.following_hash
    else
        @following_hash = {}
    end

    render :index
  end

  def show
    @user = User.includes(:picture, :followers, :following, posts: [:likers, :comments, :author, :picture, :likes]).find(params[:id])
    @following_hash = {}
    if logged_in?
      @following_hash[@user.id] = @user.passive.find_by(follower_id: current_user.id)
    end
    render :show
  end

  def search
    @users = User.includes(:picture).all
    render :search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      upload_avatar(@user)
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def upload_avatar(user)
    puts "Avatar params: #{avatar_url_params}"
    Picture.create({url: avatar_url_params["avatar_url"],
                    thumb_url: avatar_url_params["avatar_url"],
                    imageable_id: (user.id),
                    imageable_type: "User" })
  end


  private

  def user_params
    params.require(:user).permit(:password, :username, :quote)
  end

  def avatar_url_params
    params.require(:user).permit(:avatar_url)
  end

end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container">
    <video muted autoplay="" loop="" id="vid"> -->
      <source src="http://res.cloudinary.com/frankyg/video/upload/v1450158806/nap_aeuuib.mp4" type="video/mp4">
    </video>
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
          <div class="panel-heading">
              <img class="login-logo" src="http://i.imgur.com/GCUWZNK.png" >
          </div>

            <div style="padding-top:30px" class="panel-body" >
                <form action="<%= users_url %>" method="post" id="loginform" class="form-horizontal" role="form">
                    <%= auth_token_input %>

                    <div style="margin-bottom: 1px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="user[username]" value="<%= @user.username %>" placeholder="Enter username">
                    </div>

                    <div style="margin-bottom: 1px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-comment"></i></span>
                        <input id="login-username" type="text" class="form-control" name="user[quote]" value="<%= @user.quote %>" placeholder="Enter your headline">
                    </div>

                    <div style="margin-bottom: 10px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="user[password]" placeholder="Enter password">
                    </div>

                    <div style="margin-top:10px" class="form-group">
                        <div class="col-sm-12 controls">
                          <button style="margin-bottom:10px" class="btn btn-default photo-upload form-control" id="avatar-upload">Avatar Upload</button>
                          <button type="submit" id="sign-up-button" name="go" class="btn btn-lg btn-primary btn-block">Sign Up!</button>
                        </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-12 control">
                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                            Already have an account?
                        <a href="<%= new_session_url %> ">
                            Login Here
                        </a>
                        </div>
                      </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
  $("#avatar-upload").on("click", function(event){
    event.preventDefault();
    var self = this;
    var image = "";
    var thumbURL = "";
    var url = "";
    cloudinary.openUploadWidget(CLOUDINARY_OPTIONS, function(error, result){
      var data = result[0];
      var image = data.public_id + "." + data.format;
      self.image = image;
      self.thumbURL = "https://res.cloudinary.com/frankyg/image/upload/c_scale,w_300/" + image;
      $('<input>').attr({
        type: 'hidden',
        name: 'user[avatar_url]',
        value: self.thumbURL
      }).appendTo('form');
    });
})

</script>